file.upload-dir=uploads

# Maximum size per file
spring.servlet.multipart.max-file-size=50MB

# Maximum total request size (all files)
spring.servlet.multipart.max-request-size=100MB




logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=DEBUG